name: Build and Deploy Docker

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build-image-and-push-job:
    runs-on : ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v5
      
      - name: build-docker-image and push to github
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ${{github.event.repository.name}}
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}